version: "3"
services:
  mongo:
    image: mongo:3.7-jessie
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: password
  mongo_express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - 8081:8081
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: password
  parse_dashboard:
    image: parseplatform/parse-dashboard
    depends_on:
      - parse_server
    ports:
      - 4040:4040
    environment:
      PARSE_DASHBOARD_SERVER_URL: ${PARSE_DASHBOARD_SERVER_URL:-http://localhost:1337/parse}
      PARSE_DASHBOARD_MASTER_KEY: ${PARSE_DASHBOARD_MASTER_KEY:-NzVjZDNkZTcxMGI4NGMzYmJiYTZlMzIw}
      PARSE_DASHBOARD_APP_ID: ${PARSE_DASHBOARD_APP_ID:-ZTVkZTNhODU1MDhhY2YwOWNhNGI5ZDcz}
      PARSE_DASHBOARD_APP_NAME: ${PARSE_DASHBOARD_APP_NAME:-parse_dev}
      PARSE_DASHBOARD_ALLOW_INSECURE_HTTP: ${PARSE_DASHBOARD_ALLOW_INSECURE_HTTP:-true}
      PARSE_DASHBOARD_USER_ID: ${PARSE_DASHBOARD_USER_ID:-parse}
      PARSE_DASHBOARD_USER_PASSWORD: ${PARSE_DASHBOARD_USER_PASSWORD:-parse}
  parse_server:
    image: eltonplima/parse-server
    volumes:
      - ${PARSE_SERVER_CLOUDCODE_DIR:-/tmp/cloudcode}:/parse-server/cloud
    build:
      context: ./parse_server
    depends_on:
      - mongo
    ports:
      - 1337:1337
    environment:
      PARSE_SERVER_APPLICATION_ID: ${PARSE_APPLICATION_ID:-ZTVkZTNhODU1MDhhY2YwOWNhNGI5ZDcz}
      PARSE_SERVER_MASTER_KEY: ${PARSE_MASTER_KEY:-NzVjZDNkZTcxMGI4NGMzYmJiYTZlMzIw}
      PARSE_SERVER_JAVASCRIPT_KEY: ${PARSE_SERVER_JAVASCRIPT_KEY:-NTM2MzhiOGY1YjFmYzYyZmQ0NTY3Y2Vj}
      PARSE_SERVER_REST_API_KEY: ${PARSE_SERVER_REST_API_KEY:-NjNjN2M2N2VjOWIxNDI5YTdkY2E3NTMx}
      PARSE_SERVER_DATABASE_URI: ${PARSE_SERVER_DATABASE_URI:-mongodb://mongo/dev}
      PARSE_SERVER_APP_NAME: ${PARSE_SERVER_APP_NAME:-development}
      PARSE_SERVER_URL: ${PARSE_SERVER_URL:-http://0.0.0.0:1337/parse}
      PARSE_SERVER_CLOUD: ${PARSE_SERVER_CLOUD:-./cloud/main.js}
      # PARSE_SERVER_ANALYTICS_ADAPTER: ${PARSE_SERVER_ANALYTICS_ADAPTER:-analyticsAdapter}
      # PARSE_SERVER_FILES_ADAPTER: ${PARSE_SERVER_FILES_ADAPTER:-filesAdapter}
      # PARSE_SERVER_PUSH: ${PARSE_SERVER_PUSH:-push}
      # PARSE_SERVER_SCHEDULED_PUSH: ${PARSE_SERVER_SCHEDULED_PUSH:-scheduledPush}
      # PARSE_SERVER_LOGGER_ADAPTER: ${PARSE_SERVER_LOGGER_ADAPTER:-loggerAdapter}
      # JSON_LOGS: ${JSON_LOGS:-jsonLogs}
      # PARSE_SERVER_LOGS_FOLDER: ${PARSE_SERVER_LOGS_FOLDER:-logsFolder}
      # VERBOSE: ${VERBOSE:-verbose}
      # PARSE_SERVER_LOG_LEVEL: ${PARSE_SERVER_LOG_LEVEL:-logLevel}
      # SILENT: ${SILENT:-silent}
      # PARSE_SERVER_DATABASE_URI: ${PARSE_SERVER_DATABASE_URI:-databaseURI}
      # PARSE_SERVER_DATABASE_OPTIONS: ${PARSE_SERVER_DATABASE_OPTIONS:-databaseOptions}
      # PARSE_SERVER_DATABASE_ADAPTER: ${PARSE_SERVER_DATABASE_ADAPTER:-databaseAdapter}
      # PARSE_SERVER_COLLECTION_PREFIX: ${PARSE_SERVER_COLLECTION_PREFIX:-collectionPrefix}
      # PARSE_SERVER_CLIENT_KEY: ${PARSE_SERVER_CLIENT_KEY:-clientKey}
      # PARSE_SERVER_JAVASCRIPT_KEY: ${PARSE_SERVER_JAVASCRIPT_KEY:-javascriptKey}
      # PARSE_SERVER_DOT_NET_KEY: ${PARSE_SERVER_DOT_NET_KEY:-dotNetKey}
      # PARSE_SERVER_READ_ONLY_MASTER_KEY: ${PARSE_SERVER_READ_ONLY_MASTER_KEY:-readOnlyMasterKey}
      # PARSE_SERVER_WEBHOOK_KEY: ${PARSE_SERVER_WEBHOOK_KEY:-webhookKey}
      # PARSE_SERVER_FILE_KEY: ${PARSE_SERVER_FILE_KEY:-fileKey}
      # PARSE_SERVER_USER_SENSITIVE_FIELDS: ${PARSE_SERVER_USER_SENSITIVE_FIELDS:-userSensitiveFields}
      # PARSE_SERVER_ENABLE_ANON_USERS: ${PARSE_SERVER_ENABLE_ANON_USERS:-enableAnonymousUsers}
      # PARSE_SERVER_ALLOW_CLIENT_CLASS_CREATION: ${PARSE_SERVER_ALLOW_CLIENT_CLASS_CREATION:-allowClientClassCreation}
      # PARSE_SERVER_AUTH_PROVIDERS: ${PARSE_SERVER_AUTH_PROVIDERS:-auth}
      # PARSE_SERVER_MAX_UPLOAD_SIZE: ${PARSE_SERVER_MAX_UPLOAD_SIZE:-maxUploadSize}
      # PARSE_SERVER_VERIFY_USER_EMAILS: ${PARSE_SERVER_VERIFY_USER_EMAILS:-verifyUserEmails}
      # PARSE_SERVER_PREVENT_LOGIN_WITH_UNVERIFIED_EMAIL: ${PARSE_SERVER_PREVENT_LOGIN_WITH_UNVERIFIED_EMAIL:-preventLoginWithUnverifiedEmail}
      # PARSE_SERVER_EMAIL_VERIFY_TOKEN_VALIDITY_DURATION: ${PARSE_SERVER_EMAIL_VERIFY_TOKEN_VALIDITY_DURATION:-emailVerifyTokenValidityDuration}
      # PARSE_SERVER_ACCOUNT_LOCKOUT: ${PARSE_SERVER_ACCOUNT_LOCKOUT:-accountLockout}
      # PARSE_SERVER_PASSWORD_POLICY: ${PARSE_SERVER_PASSWORD_POLICY:-passwordPolicy}
      # PARSE_SERVER_CACHE_ADAPTER: ${PARSE_SERVER_CACHE_ADAPTER:-cacheAdapter}
      # PARSE_SERVER_EMAIL_ADAPTER: ${PARSE_SERVER_EMAIL_ADAPTER:-emailAdapter}
      # PARSE_PUBLIC_SERVER_URL: ${PARSE_PUBLIC_SERVER_URL:-publicServerURL}
      # PARSE_SERVER_CUSTOM_PAGES: ${PARSE_SERVER_CUSTOM_PAGES:-customPages}
      # PARSE_SERVER_LIVE_QUERY: ${PARSE_SERVER_LIVE_QUERY:-liveQuery}
      # PARSE_SERVER_SESSION_LENGTH: ${PARSE_SERVER_SESSION_LENGTH:-sessionLength}
      # PARSE_SERVER_MAX_LIMIT: ${PARSE_SERVER_MAX_LIMIT:-maxLimit}
      # PARSE_SERVER_EXPIRE_INACTIVE_SESSIONS: ${PARSE_SERVER_EXPIRE_INACTIVE_SESSIONS:-expireInactiveSessions}
      # PARSE_SERVER_REVOKE_SESSION_ON_PASSWORD_RESET: ${PARSE_SERVER_REVOKE_SESSION_ON_PASSWORD_RESET:-revokeSessionOnPasswordReset}
      # PARSE_SERVER_SCHEMA_CACHE_TTL: ${PARSE_SERVER_SCHEMA_CACHE_TTL:-schemaCacheTTL}
      # PARSE_SERVER_CACHE_TTL: ${PARSE_SERVER_CACHE_TTL:-cacheTTL}
      # PARSE_SERVER_CACHE_MAX_SIZE: ${PARSE_SERVER_CACHE_MAX_SIZE:-cacheMaxSize}
      # PARSE_SERVER_ENABLE_SINGLE_SCHEMA_CACHE: ${PARSE_SERVER_ENABLE_SINGLE_SCHEMA_CACHE:-enableSingleSchemaCache}
      # PARSE_SERVER_OBJECT_ID_SIZE: ${PARSE_SERVER_OBJECT_ID_SIZE:-objectIdSize}
      # PORT: ${PORT:-port}
      # PARSE_SERVER_HOST: ${PARSE_SERVER_HOST:-host}
      # PARSE_SERVER_MOUNT_PATH: ${PARSE_SERVER_MOUNT_PATH:-mountPath}
      # PARSE_SERVER_CLUSTER: ${PARSE_SERVER_CLUSTER:-cluster}
      # PARSE_SERVER_MIDDLEWARE: ${PARSE_SERVER_MIDDLEWARE:-middleware}
      # PARSE_SERVER_START_LIVE_QUERY_SERVER: ${PARSE_SERVER_START_LIVE_QUERY_SERVER:-startLiveQueryServer}
      # PARSE_SERVER_LIVE_QUERY_SERVER_OPTIONS: ${PARSE_SERVER_LIVE_QUERY_SERVER_OPTIONS:-liveQueryServerOptions}
# curl -X POST -H "X-Parse-Application-Id: ZTVkZTNhODU1MDhhY2YwOWNhNGI5ZDcz" -H "Content-Type: application/json" -H "X-Parse-REST-API-Key: NjNjN2M2N2VjOWIxNDI5YTdkY2E3NTMx" -H "X-Parse-Master-Key: " -d '{"score":1337,"playerName":"Sean Plott","cheatMode":false}' http://localhost:1337/parse/classes/GameScore
# curl -X POST -H "X-Parse-Application-Id: ZTVkZTNhODU1MDhhY2YwOWNhNGI5ZDcz" -H "Content-Type: application/json" -H "X-Parse-REST-API-Key: NjNjN2M2N2VjOWIxNDI5YTdkY2E3NTMx" http://localhost:1337/parse/functions/hello
